defmodule Zodium do
  @moduledoc """
  Zig-powered libsodium bindings for Elixir.
  """

  use Zig,
    otp_app: :zigler,
    c: [link_lib: {:system, "sodium"}],
    callbacks: [:on_load]

  defp __on_load__, do: nil

  ~Z"""
  const std = @import("std");
  const assert = std.debug.assert;

  const beam = @import("beam");
  const sodium = @cImport(@cInclude("sodium.h"));

  /// Callback to initialize libsodium's RNG.
  pub fn on_load(private: ?*?*u32, extra: beam.term) c_int {
    _ = private;
    _ = extra;
    return sodium.sodium_init();
  }

  /// Generates a random binary of the specified number of bytes.
  pub fn randombytes(size: usize) !beam.term {
    const buffer = try beam.allocator.alloc(u8, size);
    defer beam.allocator.free(buffer);

    sodium.randombytes(buffer.ptr, buffer.len);

    return beam.make(buffer, .{});
  }

  const BEFORENM_BYTES = sodium.crypto_box_BEFORENMBYTES;
  const MAC_BYTES = sodium.crypto_box_MACBYTES;
  const NONCE_BYTES = sodium.crypto_box_NONCEBYTES;
  const PUBLIC_KEY_BYTES = sodium.crypto_box_PUBLICKEYBYTES;
  const SEAL_BYTES = sodium.crypto_box_SEALBYTES;
  const SECRET_KEY_BYTES = sodium.crypto_box_SECRETKEYBYTES;

  pub const Keypair = struct {
    public: [PUBLIC_KEY_BYTES]u8 = [_]u8{ 0 } ** PUBLIC_KEY_BYTES,
    secret: [SECRET_KEY_BYTES]u8 = [_]u8{ 0 } ** SECRET_KEY_BYTES,
  };

  /// Generates a keypair for public-key cryptography.
  pub fn box_keypair() Keypair {
    var pair = Keypair{};

    _ = sodium.crypto_box_keypair(&pair.public, &pair.secret);

    return pair;
  }

  /// Encrypts a message with the given nonce and keys. Signed by the secret
  /// key, encrypted with a shared secret key generated by the public key and
  /// the nonce.
  ///
  /// WARNING: Do not re-use a nonce with the same keys. Generate a new one for
  /// each message.
  pub fn box(msg: []u8, nonce: [NONCE_BYTES]u8, pk: [PUBLIC_KEY_BYTES]u8, sk: [SECRET_KEY_BYTES]u8) !beam.term {
    const ciphertext = try beam.allocator.alloc(u8, MAC_BYTES + msg.len);
    defer beam.allocator.free(ciphertext);

    const ret = sodium.crypto_box_easy(ciphertext.ptr, msg.ptr, msg.len, &nonce, &pk, &sk);
    assert(ret == 0);

    return beam.make(ciphertext, .{});
  }

  /// Decrypt a message encrypted with `box`.
  ///
  /// The same nonce and coordinate keys are used to regenerate the shared
  /// secret used to do the encryption. That is, if alice.public_key and
  /// bob.secret_key were used in `box`, `box_open` should be passed
  /// bob.public_key and alice.secret_key.
  pub fn box_open(ciphertext: []u8, nonce: [NONCE_BYTES]u8, pk: [PUBLIC_KEY_BYTES]u8, sk: [SECRET_KEY_BYTES]u8) !beam.term {
    if (ciphertext.len <= MAC_BYTES) {
      return beam.make_error_pair("Not sodium-encrypted", .{});
    }

    const plaintext = try beam.allocator.alloc(u8, ciphertext.len - MAC_BYTES);
    defer beam.allocator.free(plaintext);

    const err = sodium.crypto_box_open_easy(plaintext.ptr, ciphertext.ptr, ciphertext.len, &nonce, &pk, &sk);

    if (err == 0) {
      return beam.make(.{.ok, plaintext}, .{});
    } else {
      return beam.make_error_pair(.failed_verification, .{});
    }
  }

  /// Anonymously encrypt a message using a public key.
  pub fn box_seal(msg: []u8, pk: [PUBLIC_KEY_BYTES]u8) !beam.term {
    const ciphertext = try beam.allocator.alloc(u8, msg.len + SEAL_BYTES);
    defer beam.allocator.free(ciphertext);

    _ = sodium.crypto_box_seal(ciphertext.ptr, msg.ptr, msg.len, &pk);

    return beam.make(ciphertext, .{});
  }

  /// Decrypt a message from an unknown sender.
  pub fn box_seal_open(ciphertext: []u8, pk: [PUBLIC_KEY_BYTES]u8, sk: [SECRET_KEY_BYTES]u8) !beam.term {
    if (ciphertext.len <= SEAL_BYTES) {
      return beam.make_error_pair("Not sodium-encrypted", .{});
    }

    const plaintext = try beam.allocator.alloc(u8, ciphertext.len - SEAL_BYTES);
    defer beam.allocator.free(plaintext);

    const err = sodium.crypto_box_seal_open(plaintext.ptr, ciphertext.ptr, ciphertext.len, &pk, &sk);

    if (err == 0) {
      return beam.make(.{.ok, plaintext}, .{});
    } else {
      return beam.make_error_pair(.failed_verification, .{});
    }
  }
  """
end
